### ISSUE TITLE
Associated Information from Stores Object

### ISSUE THREAD

**Issue by corejola** [corejola/Project-01#15]
In the Store Locator API, the stores object is based on search parameters (lat, lng & distance). The Product Data and the Retailer information are not, they are constant. Information from the Stores object referencing items from the Product Data and the Retailer Information Object.

Need resolution on how to associate the information between the objects that are constant and the object that is search related. Potentially use lodash JS library.

**Comment by lorrainebaynosa** [comment]
I was having problems with that too because you can only correlate them with their IDs but the loops are outside of the scope for getting them to load on the page with the other store info

**Comment by lorrainebaynosa** [comment]
Completed. Code working. See pull request for Lorriemarker.

**Comment by corejola** [comment]
Closed with merge of finalLodash-vanilla branch
